// Textos da Dashboard (pt-BR), no lugar do i18n do projeto original.
export const TEXTOS = {
  carregando: 'Carregando dados do clima...',
  erroBusca: 'Não foi possível buscar os dados de clima agora. Tentando de novo em instantes.',
  hoje: 'Hoje',
  temperatura: 'Temperatura',
  online: 'Online',
  offline: 'Offline',
  expandirMapa: 'Expandir mapa',
  escolherEstado: 'Escolher estado',
  escolherCidade: 'Escolher cidade',
  carregandoCidades: 'Carregando cidades...',
  localizando: 'Localizando...',
  previsaoTitulo: 'Previsão do tempo',
  previsaoSubtitulo: 'Previsão para os próximos 15 dias. Toque num dia pra ver a previsão por período.',
  previsaoPorPeriodo: 'Previsão por período',
  proximasHoras: 'Próximas horas',
  horaAHora: 'Hora a hora',
  agora: 'Agora',
  turnoManha: 'Manhã',
  turnoTarde: 'Tarde',
  turnoNoite: 'Noite',
  previsaoIndisponivel: 'Previsão indisponível no momento.',
  pontoOrvalho: 'Ponto de orvalho',
  indiceUV: 'Índice UV',
  precipitacao24h: 'Precipitação (24h)',
  visibilidade: 'Visibilidade',
  nascerSol: 'Nascer do sol',
  porSol: 'Pôr do sol',
  condicaoAtual: 'Condição atual',
  fechar: 'Fechar',
}
