# Generated by Django 5.2.6 on 2026-09-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_ibge', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ['uf', 'nome'],
            },
        ),
    ]
