# Generated by Django 5.2.6 on 2026-09-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoMaritimo',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ponto marítimo',
                'verbose_name_plural': 'pontos marítimos',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
