# Generated by Django 5.2.6 on 2026-09-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_seed_pontos_maritimos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontomaritimo',
            name='regiao',
            field=models.CharField(choices=[('costa-verde', 'Costa Verde'), ('rio', 'Rio de Janeiro (capital)'), ('niteroi-marica', 'Niterói e Maricá'), ('lagos', 'Região dos Lagos'), ('norte', 'Norte Fluminense')], default='rio', max_length=20),
        ),
    ]
