# Generated by Django 5.2.6 on 2026-09-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0005_mais_pontos_maritimos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontomaritimo',
            name='orientacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
